FORMAT: 1A
HOST: https://www.geodesignhub.com/api/v1

# Geodesignhub API

Geodesignhub API exposes a number of functionalities of the tool for developers to build applications and plugins with the tool. The API is a JSON-based REST API and uses standard HTTP response codes to indicate API errors.


#### Token Authentication
Geodesignhub exposes project information via the API and is linked to user accounts via Token Authentication. Since the token is linked to the user, all the projects that the user is part of are accessible using the token. Currently, tokens have an expiry of six months after which a new token can be issued.

You can get your Token by opening the [API page](https://www.geodesignhub.com/api/token/) on Geodesignhub.


#### Access
Geodesignhub supports only **https://** connections via the API. ``http://`` connections will be given a automatic HTTP 301 response.


#### Pagination
Geodesignhub API responses are generally paginated. The default page size is 10; you can alter this by adding the ``page_size`` parameter to your request.


#### Response Codes
The API uses standard HTTP response codes to communicate the status of the request. In general, 2xx codes signify success and 4xx codes signify failure, and these codes are generally associated with an invalid parameter being provided in the request. A 5xx code is a general server failure on our side. Please contact our support team if you encounter 5xx errors.

## Group Projects API
Resources related to projects on Geodesignhub.

## Projects Collection [/projects/]

### List all projects [GET]
Returns a list of projects that has the current user as a member.
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)
        
        [
          {
            "id": "5c84b38a16ebeed0",
            "projecttitle": "Cagliari geodesign",
            "projectdesc": "Alternative futures for Metro Cagliari"
          },
          {
            "id": "f05bf015a514a67c",
            "projecttitle": "Phoenix Geodesign",
            "projectdesc": "Alternative futures for Phoenix, Arizona"
          }
        ]


## Project Detail [/projects/{projectid}/]

### Get a single project [GET]
Returns the title and description of the selected project. Project name is a sixteen character hash of the project.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

            {
              "id": "5c84b38a16ebeed0",
              "projecttitle": "lego geodesign",
              "projectdesc": "lgd",
              "startdate": "2016-11-15",
              "projecttype": "free"
            }

## Project Members [/projects/{projectid}/members/]

### List members of a project [GET]
Returns a list of all the usernames that are a part of the project.


+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string

+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        {
          "members": [
            {
              "username": "ufeusr1"
            },
            {
              "username": "ufeusr2"
            },
            {
              "username": "ufeusr3"
            }
          ]
        }

## Project Study Area Bounds [/projects/{projectid}/bounds/]

### Get project bounds  [GET]
Returns a string with bounding box for the project study area coordinates in a `southwest_lng,southwest_lat,northeast_lng,northeast_lat` format.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        {
          "bounds": "-0.11569976806640624,51.49624032118747,-0.06420135498046875,51.52829020697338"
        }

## Project Study Area Center [/projects/{projectid}/center/]

### Get project center  [GET]
Returns a string with center of the study area in `longitude,latitude` format. 

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        {
          "center": "-0.1567,51.5041"
        }

                
## Project Constraints [/projects/{projectid}/constraints/]

### Get project constraints [GET]
Returns a GeoJSON geometry of constraints set within the project area.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        {
          "geojson": {
            "type": "FeatureCollection",
            "features": [
              {
                "geometry": {
                  "type": "Polygon",
                  "coordinates": [
                    [
                      [
                        -0.13458251953125,
                        51.49891200625809
                      ],
                      [
                        -0.11260986328124999,
                        51.48651406499528
                      ],
                      [
                        -0.1702880859375,
                        51.473257364513714
                      ],
                      [
                        -0.1847076416015625,
                        51.46812470399791
                      ],
                      [
                        -0.17990112304687497,
                        51.50062180251775
                      ],
                      [
                        -0.18745422363281247,
                        51.5091698216777
                      ],
                      [
                        -0.1888275146484375,
                        51.5177162373547
                      ],
                      [
                        -0.17852783203125,
                        51.52327054772943
                      ],
                      [
                        -0.17234802246093747,
                        51.52327054772943
                      ],
                      [
                        -0.13458251953125,
                        51.49891200625809
                      ],
                      [
                        -0.13458251953125,
                        51.49891200625809
                      ]
                    ]
                  ]
                },
                "type": "Feature",
                "properties": {
                  "areatype": "constraints",
                  "author": "ufeusr1",
                  "color": "#343434",
                  "diagramid": 2,
                  "sysid": 1
                }
              }
            ]
          },
          "sysid": 1,
          "rank": 0,
          "id": 0,
          "description": "No Description Added. Please add one.",
          "length": 0,
          "area": 16791.702
        }

## Project Boundaries [/projects/{projectid}/boundaries/]

### Get project boundaries [GET]
Returns a GeoJSON geometry of the first boundary set within the project area.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        {
            "geojson": {
                "type": "FeatureCollection",
                "features": [
                    {
                        "type": "Feature",
                        "properties": {
                            "bname": "Boundary 1",
                            "areatype": "boundaries",
                            "color": "#a6cee3",
                            "author": "ufeusr1"
                        },
                        "geometry": {
                            "coordinates": [
                                [
                                    [
                                        38.989019,
                                        37.180636
                                    ],
                                    [
                                        38.989191,
                                        37.166958
                                    ],
                                    [
                                        39.004469,
                                        37.166411
                                    ],
                                    [
                                        39.006529,
                                        37.182414
                                    ],
                                    [
                                        38.989019,
                                        37.180636
                                    ]
                                ]
                            ],
                            "type": "Polygon"
                        }
                    },
                    {
                        "type": "Feature",
                        "properties": {
                            "bname": "Boundary 1",
                            "areatype": "boundaries",
                            "color": "#a6cee3",
                            "author": "ufeusr1"
                        },
                        "geometry": {
                            "coordinates": [
                                [
                                    [
                                        39.013395,
                                        37.182277
                                    ],
                                    [
                                        39.011679,
                                        37.166
                                    ],
                                    [
                                        39.032106,
                                        37.167368
                                    ],
                                    [
                                        39.03039,
                                        37.18214
                                    ],
                                    [
                                        39.013395,
                                        37.182277
                                    ]
                                ]
                            ],
                            "type": "Polygon"
                        }
                    }
                ]
            },
            "description": "First Boundaries"
        }

## Project Second Boundaries [/projects/{projectid}/secondboundaries/]

### Get second project boundaries [GET]
Returns a GeoJSON geometry of second boundaries set within the project area. (Upto two boundaries can be set in a project)

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        {
            "geojson": {
                "type": "FeatureCollection",
                "features": [
                    {
                        "type": "Feature",
                        "properties": {
                            "bname": "Boundary 1",
                            "areatype": "boundaries",
                            "color": "#a6cee3",
                            "author": "ufeusr1"
                        },
                        "geometry": {
                            "coordinates": [
                                [
                                    [
                                        38.989019,
                                        37.180636
                                    ],
                                    [
                                        38.989191,
                                        37.166958
                                    ],
                                    [
                                        39.004469,
                                        37.166411
                                    ],
                                    [
                                        39.006529,
                                        37.182414
                                    ],
                                    [
                                        38.989019,
                                        37.180636
                                    ]
                                ]
                            ],
                            "type": "Polygon"
                        }
                    },
                    {
                        "type": "Feature",
                        "properties": {
                            "bname": "Boundary 1",
                            "areatype": "boundaries",
                            "color": "#a6cee3",
                            "author": "ufeusr1"
                        },
                        "geometry": {
                            "coordinates": [
                                [
                                    [
                                        39.013395,
                                        37.182277
                                    ],
                                    [
                                        39.011679,
                                        37.166
                                    ],
                                    [
                                        39.032106,
                                        37.167368
                                    ],
                                    [
                                        39.03039,
                                        37.18214
                                    ],
                                    [
                                        39.013395,
                                        37.182277
                                    ]
                                ]
                            ],
                            "type": "Polygon"
                        }
                    }
                ]
            },
            "description": "Second Boundaries"
        }


## Group Diagrams API
Resources related to diagrams on Geodesignhub.

## Diagrams Collection [/projects/{projectid}/diagrams/]

### List project diagrams [GET]
Returns all the diagrams for the project by ID and description.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

            [
              {
                "id": 7,
                "worlddescription": "ase",
                "author": "ufeusr1",
                "created_at": "2018-08-26T20:53:25.838663",
                "rank": 1,
                "sysid": 2
              },
              {
                "id": 8,
                "worlddescription": "ce",
                "author": "ufeusr1",
                "created_at": "2018-01-26T20:53:25.838663",
                "rank": 1,
                "sysid": 1
              },
              {
                "id": 9,
                "worlddescription": "32",
                "author": "ufeusr1",
                "created_at": "2018-02-02T20:53:25.838663",
                "rank": 2,
                "sysid": 1
              }
            ]


## All Diagrams [/projects/{projectid}/diagrams/all/]

### Get details of all diagrams [GET]
Returns the a list of Diagram geometries and properties for all the diagrams in the project. 

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string


+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

            [
              {
                "geojson": {
                  "type": "FeatureCollection",
                  "features": [
                    {
                      "geometry": {
                        "type": "Polygon",
                        "coordinates": [
                          [
                            [
                              -0.09514331817626952,
                              51.51555307745177
                            ],
                            [
                              -0.09394168853759766,
                              51.51523260058079
                            ],
                            [
                              -0.08668899536132812,
                              51.51549966479653
                            ],
                            [
                              -0.0856161117553711,
                              51.515659902574384
                            ],
                            [
                              -0.08085250854492186,
                              51.51547295844541
                            ],
                            [
                              -0.08020877838134766,
                              51.51531272000991
                            ],
                            [
                              -0.07797718048095703,
                              51.51437798456801
                            ],
                            [
                              -0.07746219635009766,
                              51.51395067054886
                            ],
                            [
                              -0.07741928100585936,
                              51.51352335252112
                            ],
                            [
                              -0.07784843444824219,
                              51.5129891993494
                            ],
                            [
                              -0.07973670959472656,
                              51.51280224425956
                            ],
                            [
                              -0.0832986831665039,
                              51.51309603048481
                            ],
                            [
                              -0.08703231811523438,
                              51.51309603048481
                            ],
                            [
                              -0.08870601654052734,
                              51.5129891993494
                            ],
                            [
                              -0.09029388427734374,
                              51.51325627671818
                            ],
                            [
                              -0.09162425994873047,
                              51.51365688983539
                            ],
                            [
                              -0.0960874557495117,
                              51.51456493319091
                            ],
                            [
                              -0.09724617004394531,
                              51.514992241447835
                            ],
                            [
                              -0.0972890853881836,
                              51.51568660881589
                            ],
                            [
                              -0.09552955627441406,
                              51.51571331504175
                            ],
                            [
                              -0.09514331817626952,
                              51.51555307745177
                            ],
                            [
                              -0.09514331817626952,
                              51.51555307745177
                            ]
                          ]
                        ]
                      },
                      "type": "Feature",
                      "properties": {
                        "areatype": "project",
                        "author": "ufeusr1",
                        "color": "#071ac8",
                        "diagramid": 5,
                        "sysid": 1,
                        "systag": "Small buildings, low density housing"
                      }
                    }
                  ]
                },
                "sysid": 1,
                "rank": 1,
                "id": 1,
                "description": "testing",
                "length": 0,
                "area": 16791.702,
                "cost_override": 100,
                "cost_override_type": "total",                
                "created_at": "2018-08-26 20:57:02"
              },
              {
                "geojson": {
                  "type": "FeatureCollection",
                  "features": [
                    {
                      "geometry": {
                        "type": "Polygon",
                        "coordinates": [
                          [
                            [
                              -0.1064300537109375,
                              51.5212411667077
                            ],
                            [
                              -0.07432937622070312,
                              51.50927666176991
                            ],
                            [
                              -0.06299972534179688,
                              51.505537109466715
                            ],
                            [
                              -0.06282806396484375,
                              51.50468231156
                            ],
                            [
                              -0.06420135498046875,
                              51.504148054725356
                            ],
                            [
                              -0.07656097412109375,
                              51.50607135001545
                            ],
                            [
                              -0.08737564086914062,
                              51.5089561407416
                            ],
                            [
                              -0.09990692138671875,
                              51.51066556016948
                            ],
                            [
                              -0.1078033447265625,
                              51.51087923308819
                            ],
                            [
                              -0.10951995849609375,
                              51.51525930707282
                            ],
                            [
                              -0.11484146118164062,
                              51.522522891558964
                            ],
                            [
                              -0.11243820190429688,
                              51.522629700334875
                            ],
                            [
                              -0.1064300537109375,
                              51.5212411667077
                            ],
                            [
                              -0.1064300537109375,
                              51.5212411667077
                            ]
                          ]
                        ]
                      },
                      "type": "Feature",
                      "properties": {
                        "areatype": "policy",
                        "author": "ufeusr1",
                        "color": "#071ac8",
                        "diagramid": 7,
                        "sysid": 1,
                        "systag": "Small buildings, low density housing"
                      }
                    }
                  ]
                },
                "sysid": 1,
                "rank": 2,
                "id": 2,
                "description": "new polciy",
                "length": 0,
                "area": 16791.702,
                "cost_override": 0,
                "cost_override_type": "total",                
                "created_at": "2018-08-26 20:57:02"
              },
              {
                "geojson": {
                  "type": "FeatureCollection",
                  "features": [
                    {
                      "geometry": {
                        "type": "Polygon",
                        "coordinates": [
                          [
                            [
                              -0.09479999542236328,
                              51.51472517425703
                            ],
                            [
                              -0.09415626525878906,
                              51.511760623284765
                            ],
                            [
                              -0.09419918060302733,
                              51.509837568143645
                            ],
                            [
                              -0.09758949279785156,
                              51.510558723334285
                            ],
                            [
                              -0.09883403778076172,
                              51.51103948711957
                            ],
                            [
                              -0.09836196899414062,
                              51.511760623284765
                            ],
                            [
                              -0.0990915298461914,
                              51.515900258184224
                            ],
                            [
                              -0.09492874145507812,
                              51.515900258184224
                            ],
                            [
                              -0.09479999542236328,
                              51.51472517425703
                            ],
                            [
                              -0.09479999542236328,
                              51.51472517425703
                            ]
                          ]
                        ]
                      },
                      "type": "Feature",
                      "properties": {
                        "areatype": "project",
                        "author": "ufeusr1",
                        "color": "#fc1999",
                        "diagramid": 8,
                        "sysid": 2,
                        "systag": "Large buildings, Industry, commerce"
                      }
                    }
                  ]
                },
                "sysid": 2,
                "rank": 1,
                "id": 1,
                "description": "new project",
                "length": 0,
                "area": 16791.702,
                "cost_override": 100,                  
                "cost_override_type": "total",                
                "created_at": "2018-08-26 20:57:02"
              }
            ]
            
## Diagram Detail [/projects/{projectid}/diagrams/{diagramid}/]

### Get details of a diagram [GET]
Returns the a GeoJSON feature collection geometry of the diagram that is passed in the diagram ID.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + diagramid: 12 (integer) - The ID of the diagram in the form of an integer
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        {
          "geojson": {
            "type": "FeatureCollection",
            "features": [
              {
                "geometry": {
                  "type": "Polygon",
                  "coordinates": [
                    [
                      [
                        -0.09514331817626952,
                        51.51555307745177
                      ],
                      [
                        -0.09394168853759766,
                        51.51523260058079
                      ],
                      [
                        -0.08668899536132812,
                        51.51549966479653
                      ],
                      [
                        -0.0856161117553711,
                        51.515659902574384
                      ],
                      [
                        -0.08085250854492186,
                        51.51547295844541
                      ],
                      [
                        -0.08020877838134766,
                        51.51531272000991
                      ],
                      [
                        -0.07797718048095703,
                        51.51437798456801
                      ],
                      [
                        -0.07746219635009766,
                        51.51395067054886
                      ],
                      [
                        -0.07741928100585936,
                        51.51352335252112
                      ],
                      [
                        -0.07784843444824219,
                        51.5129891993494
                      ],
                      [
                        -0.07973670959472656,
                        51.51280224425956
                      ],
                      [
                        -0.0832986831665039,
                        51.51309603048481
                      ],
                      [
                        -0.08703231811523438,
                        51.51309603048481
                      ],
                      [
                        -0.08870601654052734,
                        51.5129891993494
                      ],
                      [
                        -0.09029388427734374,
                        51.51325627671818
                      ],
                      [
                        -0.09162425994873047,
                        51.51365688983539
                      ],
                      [
                        -0.0960874557495117,
                        51.51456493319091
                      ],
                      [
                        -0.09724617004394531,
                        51.514992241447835
                      ],
                      [
                        -0.0972890853881836,
                        51.51568660881589
                      ],
                      [
                        -0.09552955627441406,
                        51.51571331504175
                      ],
                      [
                        -0.09514331817626952,
                        51.51555307745177
                      ],
                      [
                        -0.09514331817626952,
                        51.51555307745177
                      ]
                    ]
                  ]
                },
                "type": "Feature",
                "properties": {
                  "areatype": "project",
                  "author": "ufeusr1",
                  "color": "#071ac8",
                  "diagramid": 5,
                  "sysid": 1,
                  "systag": "Small buildings, low density housing"
                }
              }
            ]
          },
          "sysid": 1,
          "rank": 1,
          "type": "policy",
          "id": 1,
          "description": "Forest areas to be protected",
          "length": 0,
          "area": 16791.702,
          "cost_override": 100,
          "cost_override_type": "total",
          "created_at": "2018-08-26 20:57:02"
        }

## Diagram Last Changed [/projects/{projectid}/diagrams/{diagramid}/changeid/]

### Get details last modified timestamp of a diagram [GET]
Returns the a hash of the last modified date, can be used to see if a diagram has changed from the last time it was accessed.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + diagramid: 12 (integer) - The ID of the diagram in the form of an integer
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        {
          "changehash": "57266cf8"
        }


## User Diagrams Selections [/projects/{projectid}/members/{username}/diagrams/]

### Get details diagrams selected by a user [GET]
Returns the geometry of the diagrams selected by the user for the particular project. The user has to be a member of the project.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + username: ufeusr1 (string) - The username of a user who is a member of the project

+ Response 200 (application/json)

        {
          "type": "FeatureCollection",
          "features": [
            {
              "geometry": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [
                      -0.0254058837890625,
                      51.51643437722083
                    ],
                    [
                      -0.007553100585937499,
                      51.51344322994464
                    ],
                    [
                      -0.001373291015625,
                      51.5091698216777
                    ],
                    [
                      0,
                      51.494637234974235
                    ],
                    [
                      -0.00274658203125,
                      51.49036206277271
                    ],
                    [
                      -0.0185394287109375,
                      51.4830933498849
                    ],
                    [
                      -0.0226593017578125,
                      51.4830933498849
                    ],
                    [
                      -0.031585693359375,
                      51.486941636341456
                    ],
                    [
                      -0.030212402343749997,
                      51.515579783755925
                    ],
                    [
                      -0.0254058837890625,
                      51.524552215462975
                    ],
                    [
                      -0.0254058837890625,
                      51.51643437722083
                    ],
                    [
                      -0.0254058837890625,
                      51.51643437722083
                    ]
                  ]
                ]
              },
              "type": "Feature",
              "properties": {
                "sysname": "S7",
                "areatype": "policy",
                "description": "guava",
                "author": "ufeusr2",
                "color": "#653308",
                "diagramid": 15,
                "sysid": 215,
                "rgbcolor": "[101, 51, 8]"
              }
            },
            {
              "geometry": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [
                      -0.048065185546875,
                      51.476678817400156
                    ],
                    [
                      -0.04669189453125,
                      51.473257364513714
                    ],
                    [
                      -0.076904296875,
                      51.469407923261336
                    ],
                    [
                      -0.1229095458984375,
                      51.461280258392385
                    ],
                    [
                      -0.1380157470703125,
                      51.456146250469146
                    ],
                    [
                      -0.0995635986328125,
                      51.485231326900056
                    ],
                    [
                      -0.081024169921875,
                      51.49634719159713
                    ],
                    [
                      -0.0748443603515625,
                      51.49848454717058
                    ],
                    [
                      -0.06797790527343749,
                      51.49848454717058
                    ],
                    [
                      -0.048065185546875,
                      51.476678817400156
                    ],
                    [
                      -0.048065185546875,
                      51.476678817400156
                    ]
                  ]
                ]
              },
              "type": "Feature",
              "properties": {
                "sysname": "S6",
                "areatype": "policy",
                "description": "nagpur",
                "author": "ufeusr1",
                "color": "#0a650c",
                "diagramid": 14,
                "sysid": 215,
                "rgbcolor": "[10, 101, 12]"
              }
            },
            {
              "geometry": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [
                      -0.09750366210937499,
                      51.4830933498849
                    ],
                    [
                      -0.0968170166015625,
                      51.477106480966924
                    ],
                    [
                      -0.1064300537109375,
                      51.4655581571998
                    ],
                    [
                      -0.11260986328124999,
                      51.462563670141634
                    ],
                    [
                      -0.1325225830078125,
                      51.46213587023546
                    ],
                    [
                      -0.15106201171874997,
                      51.454434786162615
                    ],
                    [
                      -0.16548156738281247,
                      51.456146250469146
                    ],
                    [
                      -0.1812744140625,
                      51.46384704579897
                    ],
                    [
                      -0.182647705078125,
                      51.467696956223385
                    ],
                    [
                      -0.17303466796874997,
                      51.47197425351888
                    ],
                    [
                      -0.163421630859375,
                      51.47368506015889
                    ],
                    [
                      -0.138702392578125,
                      51.47496812303544
                    ],
                    [
                      -0.13458251953125,
                      51.48865188163204
                    ],
                    [
                      -0.1325225830078125,
                      51.49036206277271
                    ],
                    [
                      -0.12359619140625,
                      51.49036206277271
                    ],
                    [
                      -0.09750366210937499,
                      51.4830933498849
                    ],
                    [
                      -0.09750366210937499,
                      51.4830933498849
                    ]
                  ]
                ]
              },
              "type": "Feature",
              "properties": {
                "sysname": "ege",
                "areatype": "project",
                "description": "fasef",
                "author": "ufeusr2",
                "color": "#da0a16",
                "diagramid": 2,
                "sysid": 215,
                "rgbcolor": "[218, 10, 22]"
              }
            }
          ]
        }



## Group Systems API
Resources related to systems within a project on Geodesignhub.

## Systems Collection [/projects/{projectid}/systems/]

### List project systems [GET]
Returns all the system details for the project with ID and system name.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        [
          {
            "id": 1,
            "sysname": "LDH",
            "syscolor": "#071ac8"
          },
          {
            "id": 2,
            "sysname": "HDH",
            "syscolor": "#fc1999"
          },
          {
            "id": 3,
            "sysname": "AG",
            "syscolor": "#18a81b"
          },
          {
            "id": 15,
            "sysname": "S4",
            "syscolor": "#0a650c"
          }
        ]

## System Detail [/projects/{projectid}/systems/{sysid}/]

### Get system details [GET]
Returns the details of that system such as system name, type, etc.
+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + sysid: 23 (integer) - The ID of the system in the form of an integer

+ Response 200 (application/json)

        {
          "id": 1,
          "sysname": "LDH",
          "syscolor": "#071ac8",
          "systag": "SMB",
          "syscost": 100000,
          "sysbudget": 2000000
        }


## System Diagrams [/projects/{projectid}/systems/{sysid}/diagrams/]

### Get system diagrams [GET]
Returns the IDs of all the diagrams contained in that system
+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + sysid: 23 (integer) - The ID of the system in the form of an integer

+ Response 200 (application/json)

        {
          "diagrams": [
            5,
            7,
            13,
            15,
            18
          ]
        }
## System Evaluation [/projects/{projectid}/systems/{sysid}/evaluation/]

### Get system evaluation [GET]
Returns a GeoJSON feature collection for the evaluation map for this system.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + sysid: 23 (integer) - The ID of the system in the form of an integer
    
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        {
          "geojson": {
            "type": "FeatureCollection",
            "features": [
              {
                "geometry": {
                  "type": "Polygon",
                  "coordinates": [
                    [
                      [
                        -0.21629333496093747,
                        51.5399294146093
                      ],
                      [
                        -0.208740234375,
                        51.53480425870272
                      ],
                      [
                        -0.204620361328125,
                        51.524979430024345
                      ],
                      [
                        -0.204620361328125,
                        51.514725174257
                      ],
                      [
                        -0.2066802978515625,
                        51.505750806437874
                      ],
                      [
                        -0.218353271484375,
                        51.497202145853784
                      ],
                      [
                        -0.230712890625,
                        51.49164465653034
                      ],
                      [
                        -0.24307250976562497,
                        51.48822432632349
                      ],
                      [
                        -0.2767181396484375,
                        51.48822432632349
                      ],
                      [
                        -0.2877044677734375,
                        51.49078959803455
                      ],
                      [
                        -0.292510986328125,
                        51.494637234974235
                      ],
                      [
                        -0.2931976318359375,
                        51.5091698216777
                      ],
                      [
                        -0.2849578857421875,
                        51.5283970022217
                      ],
                      [
                        -0.276031494140625,
                        51.536512708129735
                      ],
                      [
                        -0.2684783935546875,
                        51.540783551151826
                      ],
                      [
                        -0.22384643554687497,
                        51.54206472590799
                      ],
                      [
                        -0.21629333496093747,
                        51.5399294146093
                      ],
                      [
                        -0.21629333496093747,
                        51.5399294146093
                      ]
                    ]
                  ]
                },
                "type": "Feature",
                "properties": {
                  "areatype": "red",
                  "color": "#f03b20"
                }
              },
              {
                "geometry": {
                  "type": "Polygon",
                  "coordinates": [
                    [
                      [
                        -0.141448974609375,
                        51.5403564848844
                      ],
                      [
                        -0.13458251953125,
                        51.53864817973767
                      ],
                      [
                        -0.12153625488281249,
                        51.52882418070984
                      ],
                      [
                        -0.11947631835937499,
                        51.52198884392169
                      ],
                      [
                        -0.11947631835937499,
                        51.50959718054336
                      ],
                      [
                        -0.12359619140625,
                        51.50062180251775
                      ],
                      [
                        -0.1297760009765625,
                        51.49634719159713
                      ],
                      [
                        -0.1593017578125,
                        51.497202145853784
                      ],
                      [
                        -0.16754150390625,
                        51.49848454717058
                      ],
                      [
                        -0.1737213134765625,
                        51.5027589576403
                      ],
                      [
                        -0.1764678955078125,
                        51.51045188624856
                      ],
                      [
                        -0.17578125,
                        51.519425328081894
                      ],
                      [
                        -0.1627349853515625,
                        51.53523137707124
                      ],
                      [
                        -0.1544952392578125,
                        51.5399294146093
                      ],
                      [
                        -0.1483154296875,
                        51.540783551151826
                      ],
                      [
                        -0.141448974609375,
                        51.5403564848844
                      ],
                      [
                        -0.141448974609375,
                        51.5403564848844
                      ]
                    ]
                  ]
                },
                "type": "Feature",
                "properties": {
                  "areatype": "green",
                  "color": "#74c476"
                }
              },
              {
                "geometry": {
                  "type": "Polygon",
                  "coordinates": [
                    [
                      [
                        -0.05699157714843749,
                        51.56341232867588
                      ],
                      [
                        -0.050811767578125,
                        51.55999738544502
                      ],
                      [
                        -0.0439453125,
                        51.55231282551346
                      ],
                      [
                        -0.03776550292968749,
                        51.53523137707124
                      ],
                      [
                        -0.0384521484375,
                        51.5283970022217
                      ],
                      [
                        -0.04119873046875,
                        51.524552215462975
                      ],
                      [
                        -0.0446319580078125,
                        51.52198884392169
                      ],
                      [
                        -0.0501251220703125,
                        51.520707104039275
                      ],
                      [
                        -0.05699157714843749,
                        51.520707104039275
                      ],
                      [
                        -0.06797790527343749,
                        51.524124996893335
                      ],
                      [
                        -0.06866455078125,
                        51.53523137707124
                      ],
                      [
                        -0.06591796875,
                        51.54121061341155
                      ],
                      [
                        -0.07415771484375,
                        51.55487448974971
                      ],
                      [
                        -0.06797790527343749,
                        51.56255861691012
                      ],
                      [
                        -0.0624847412109375,
                        51.56426602441386
                      ],
                      [
                        -0.05699157714843749,
                        51.56341232867588
                      ],
                      [
                        -0.05699157714843749,
                        51.56341232867588
                      ]
                    ]
                  ]
                },
                "type": "Feature",
                "properties": {
                  "areatype": "green",
                  "color": "#74c476"
                }
              }
            ]
          },
          "sysid": 1
        }


## Add Project Diagram to System [/projects/{projectid}/systems/{sysid}/add/project/]

### Add a project diagram [POST]
Add a new diagram to a system

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + sysid: 23 (integer) - The ID of the system in the form of an integer


+ Request (application/json)

        {
            "geometry": {
                  "type": "FeatureCollection",
                  "features": [
                    {
                      "type": "Feature",
                      "properties": {},
                      "geometry": {
                        "type": "Polygon",
                        "coordinates": [
                          [
                            [
                              -0.09307265281677245,
                              51.516194024429446
                            ],
                            [
                              -0.09310483932495117,
                              51.51524595382876
                            ],
                            [
                              -0.09136676788330077,
                              51.51502562473659
                            ],
                            [
                              -0.09100198745727538,
                              51.515639872882986
                            ],
                            [
                              -0.09152770042419434,
                              51.51636093622468
                            ],
                            [
                              -0.09307265281677245,
                              51.51622740683744
                            ],
                            [
                              -0.09307265281677245,
                              51.516194024429446
                            ]
                          ]
                        ]
                      }
                    }
                  ]
                },
            "featuretype": "polygon",
            "description": "A new shopping mall", 
            "fundingtype":"pu"
        }
        
+ Response 200 (application/json)

        {
            "msg":"Diagram successfully Added"}
        }

## Add Policy Diagram to System [/projects/{projectid}/systems/{sysid}/add/policy/]

### Add a policy diagram [POST]
Add a new diagram to a system

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a policy in the form of an string
    + sysid: 23 (integer) - The ID of the system in the form of an integer

    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Request (application/json)

        {
            "geometry": {
                  "type": "FeatureCollection",
                  "features": [
                    {
                      "type": "Feature",
                      "properties": {},
                      "geometry": {
                        "type": "Polygon",
                        "coordinates": [
                          [
                            [
                              -0.10273933410644531,
                              51.5111730317151
                            ],
                            [
                              -0.10273933410644531,
                              51.523003529077705
                            ],
                            [
                              -0.08351325988769531,
                              51.523003529077705
                            ],
                            [
                              -0.08351325988769531,
                              51.5111730317151
                            ],
                            [
                              -0.10273933410644531,
                              51.5111730317151
                            ]
                          ]
                        ]
                      }
                    }
                  ]
                },
            "featuretype": "polygon",
            "description": "Low taxation policy",
            "fundingtype":"pu"
        }
        
+ Response 200 (application/json)

        {
            "msg":"Diagram successfully Added"}
        }


## Add Evaluation Map to a System [/projects/{projectid}/systems/{sysid}/e/map/json/{username}/]

### Add evaluation map for a user [POST]
A geoJSON object that has the updated JSON layer of either evaluation or impact data submitted to the user

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + sysid: 23 (integer) - The ID of the system in the form of an integer
    + username: ufeusr1 (string) - The username of a user who is a member of the project

    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Request (application/json)

        {
            "type":"FeatureCollection",
            "features":[
                {
                    "type":"Feature",
                    "properties":{
                        "areatype":"red"
                    },
                    "geometry":{
                        "type":"Polygon",
                        "coordinates":[
                            [
                                [
                                    -0.09307265281677245,
                                    51.516194024429446
                                ],
                                [
                                    -0.09310483932495117,
                                    51.51524595382876
                                ],
                                [
                                    -0.09136676788330077,
                                    51.51502562473659
                                ],
                                [
                                    -0.09100198745727538,
                                    51.515639872882986
                                ],
                                [
                                    -0.09152770042419434,
                                    51.51636093622468
                                ],
                                [
                                    -0.09307265281677245,
                                    51.51622740683744
                                ],
                                [
                                    -0.09307265281677245,
                                    51.516194024429446
                                ]
                            ]
                        ]
                    }
                }
            ]
        }
        
+ Response 200 (application/json)

        {
            "msg":"Data successfully posted to users."}
        }


## Add Impact Map to a System [/projects/{projectid}/systems/{sysid}/i/map/json/{username}/]

### Add a impact map for a user [POST]
A geoJSON object that has the updated JSON layer of either evaluation or impact data submitted to the user

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + sysid: 23 (integer) - The ID of the system in the form of an integer
    + username: ufeusr1 (string) - The username of a user who is a member of the project

    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Request (application/json)

        {
            "type":"FeatureCollection",
            "features":[
                {
                    "type":"Feature",
                    "properties":{
                        "areatype":"purple2"
                    },
                    "geometry":{
                        "type":"Polygon",
                        "coordinates":[
                            [
                                [
                                    -0.09307265281677245,
                                    51.516194024429446
                                ],
                                [
                                    -0.09310483932495117,
                                    51.51524595382876
                                ],
                                [
                                    -0.09136676788330077,
                                    51.51502562473659
                                ],
                                [
                                    -0.09100198745727538,
                                    51.515639872882986
                                ],
                                [
                                    -0.09152770042419434,
                                    51.51636093622468
                                ],
                                [
                                    -0.09307265281677245,
                                    51.51622740683744
                                ],
                                [
                                    -0.09307265281677245,
                                    51.516194024429446
                                ]
                            ]
                        ]
                    }
                }
            ]
        }
            
+ Response 200 (application/json)

        {
            "msg":"Data successfully posted to users."}
        }

## User System Diagram Selection [/projects/{projectid}/systems/{sysid}/{username}/diagrams/]

### Get diagrams selected in a system by user [GET]
Returns the geometry of the diagrams selected by the user for the particular project and a specific system. 

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + sysid: 23 (integer) - The ID of the system in the form of an integer
    + username: ufeusr1 (string) - The username of a user who is a member of the project

+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

            {
              "type": "FeatureCollection",
              "features": [
                {
                  "geometry": {
                    "type": "Polygon",
                    "coordinates": [
                      [
                        [
                          -0.1064300537109375,
                          51.5212411667077
                        ],
                        [
                          -0.07432937622070312,
                          51.50927666176991
                        ],
                        [
                          -0.06299972534179688,
                          51.505537109466715
                        ],
                        [
                          -0.06282806396484375,
                          51.50468231156
                        ],
                        [
                          -0.06420135498046875,
                          51.504148054725356
                        ],
                        [
                          -0.07656097412109375,
                          51.50607135001545
                        ],
                        [
                          -0.08737564086914062,
                          51.5089561407416
                        ],
                        [
                          -0.09990692138671875,
                          51.51066556016948
                        ],
                        [
                          -0.1078033447265625,
                          51.51087923308819
                        ],
                        [
                          -0.10951995849609375,
                          51.51525930707282
                        ],
                        [
                          -0.11484146118164062,
                          51.522522891558964
                        ],
                        [
                          -0.11243820190429688,
                          51.522629700334875
                        ],
                        [
                          -0.1064300537109375,
                          51.5212411667077
                        ],
                        [
                          -0.1064300537109375,
                          51.5212411667077
                        ]
                      ]
                    ]
                  },
                  "type": "Feature",
                  "properties": {
                    "areatype": "policy",
                    "color": "#071ac8",
                    "systag": "Small buildings, low density housing"
                  }
                },
                {
                  "geometry": {
                    "type": "Polygon",
                    "coordinates": [
                      [
                        [
                          -0.09514331817626952,
                          51.51555307745177
                        ],
                        [
                          -0.09394168853759766,
                          51.51523260058079
                        ],
                        [
                          -0.08668899536132812,
                          51.51549966479653
                        ],
                        [
                          -0.0856161117553711,
                          51.515659902574384
                        ],
                        [
                          -0.08085250854492186,
                          51.51547295844541
                        ],
                        [
                          -0.08020877838134766,
                          51.51531272000991
                        ],
                        [
                          -0.07797718048095703,
                          51.51437798456801
                        ],
                        [
                          -0.07746219635009766,
                          51.51395067054886
                        ],
                        [
                          -0.07741928100585936,
                          51.51352335252112
                        ],
                        [
                          -0.07784843444824219,
                          51.5129891993494
                        ],
                        [
                          -0.07973670959472656,
                          51.51280224425956
                        ],
                        [
                          -0.0832986831665039,
                          51.51309603048481
                        ],
                        [
                          -0.08703231811523438,
                          51.51309603048481
                        ],
                        [
                          -0.08870601654052734,
                          51.5129891993494
                        ],
                        [
                          -0.09029388427734374,
                          51.51325627671818
                        ],
                        [
                          -0.09162425994873047,
                          51.51365688983539
                        ],
                        [
                          -0.0960874557495117,
                          51.51456493319091
                        ],
                        [
                          -0.09724617004394531,
                          51.514992241447835
                        ],
                        [
                          -0.0972890853881836,
                          51.51568660881589
                        ],
                        [
                          -0.09552955627441406,
                          51.51571331504175
                        ],
                        [
                          -0.09514331817626952,
                          51.51555307745177
                        ],
                        [
                          -0.09514331817626952,
                          51.51555307745177
                        ]
                      ]
                    ]
                  },
                  "type": "Feature",
                  "properties": {
                    "areatype": "project",
                    "color": "#071ac8",
                    "systag": "Small buildings, low density housing"
                  }
                }
              ]
            }

## User System Projects Diagram Selection [/projects/{projectid}/systems/{sysid}/{username}/diagrams/projects/]

### Get project diagrams selected in a system by user [GET]
Returns the geometry only of project diagrams selected by the user for the particular project and a specific system. 

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + sysid: 23 (integer) - The ID of the system in the form of an integer
    + username: ufeusr1 (string) - The username of a user who is a member of the project
    
+ Request
    + Headers

            Authorization: Token ABC123
            

+ Response 200 (application/json)

        {
          "type": "FeatureCollection",
          "features": [
            {
              "geometry": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [
                      -0.09514331817626952,
                      51.51555307745177
                    ],
                    [
                      -0.09394168853759766,
                      51.51523260058079
                    ],
                    [
                      -0.08668899536132812,
                      51.51549966479653
                    ],
                    [
                      -0.0856161117553711,
                      51.515659902574384
                    ],
                    [
                      -0.08085250854492186,
                      51.51547295844541
                    ],
                    [
                      -0.08020877838134766,
                      51.51531272000991
                    ],
                    [
                      -0.07797718048095703,
                      51.51437798456801
                    ],
                    [
                      -0.07746219635009766,
                      51.51395067054886
                    ],
                    [
                      -0.07741928100585936,
                      51.51352335252112
                    ],
                    [
                      -0.07784843444824219,
                      51.5129891993494
                    ],
                    [
                      -0.07973670959472656,
                      51.51280224425956
                    ],
                    [
                      -0.0832986831665039,
                      51.51309603048481
                    ],
                    [
                      -0.08703231811523438,
                      51.51309603048481
                    ],
                    [
                      -0.08870601654052734,
                      51.5129891993494
                    ],
                    [
                      -0.09029388427734374,
                      51.51325627671818
                    ],
                    [
                      -0.09162425994873047,
                      51.51365688983539
                    ],
                    [
                      -0.0960874557495117,
                      51.51456493319091
                    ],
                    [
                      -0.09724617004394531,
                      51.514992241447835
                    ],
                    [
                      -0.0972890853881836,
                      51.51568660881589
                    ],
                    [
                      -0.09552955627441406,
                      51.51571331504175
                    ],
                    [
                      -0.09514331817626952,
                      51.51555307745177
                    ],
                    [
                      -0.09514331817626952,
                      51.51555307745177
                    ]
                  ]
                ]
              },
              "type": "Feature",
              "properties": {
                "areatype": "project",
                "color": "#071ac8",
                "systag": "Small buildings, low density housing"
              }
            }
          ]
        }


## User System Policies Diagram Selection [/projects/{projectid}/systems/{sysid}/{username}/diagrams/policies/]

### Get geometries of policy diagrams selected in a system by user [GET]
Returns the geometry only of policy diagrams selected by the user for the particular project and a specific system. 

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + sysid: 23 (integer) - The ID of the system in the form of an integer
    + username: ufeusr1 (string) - The username of a user who is a member of the project
    
+ Request
    + Headers

            Authorization: Token ABC123

+ Response 200 (application/json)

            {
              "type": "FeatureCollection",
              "features": [
                {
                  "geometry": {
                    "type": "Polygon",
                    "coordinates": [
                      [
                        [
                          -0.1064300537109375,
                          51.5212411667077
                        ],
                        [
                          -0.07432937622070312,
                          51.50927666176991
                        ],
                        [
                          -0.06299972534179688,
                          51.505537109466715
                        ],
                        [
                          -0.06282806396484375,
                          51.50468231156
                        ],
                        [
                          -0.06420135498046875,
                          51.504148054725356
                        ],
                        [
                          -0.07656097412109375,
                          51.50607135001545
                        ],
                        [
                          -0.08737564086914062,
                          51.5089561407416
                        ],
                        [
                          -0.09990692138671875,
                          51.51066556016948
                        ],
                        [
                          -0.1078033447265625,
                          51.51087923308819
                        ],
                        [
                          -0.10951995849609375,
                          51.51525930707282
                        ],
                        [
                          -0.11484146118164062,
                          51.522522891558964
                        ],
                        [
                          -0.11243820190429688,
                          51.522629700334875
                        ],
                        [
                          -0.1064300537109375,
                          51.5212411667077
                        ],
                        [
                          -0.1064300537109375,
                          51.5212411667077
                        ]
                      ]
                    ]
                  },
                  "type": "Feature",
                  "properties": {
                    "areatype": "policy",
                    "color": "#071ac8",
                    "systag": "Small buildings, low density housing"
                  }
                }
              ]
            }

## Group Change Teams API
A set of resources related to Change teams within a Geodesignhub Project

## Change Team Collection [/projects/{projectid}/cteams/]

### List all change teams [GET]
Return all the change teams for that project.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

            [
              {
                "id": 1,
                "title": "DEV"
              },
              {
                "id": 4,
                "title": "ECON"
              }
            ]  



## Change Team Detail [/projects/{projectid}/cteams/{cteamid}/]

### List designs of a change team [GET]
Returns a list of synthesis created by this change team

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + cteamid: 12 (integer) - The ID of the change team in the form of an integer

+ Response 200 (application/json)

        {
          "synthesis": [
            {
              "cteamid": 1,
              "creationdate": "2016-04-28T22:24:21.968000",
              "id": "PHBN4B9H1KDBHKPK",
              "description": "v3"
            },
            {
              "cteamid": 1,
              "creationdate": "2016-04-30T13:36:54.304000",
              "id": "9F79977KO8KB35GM",
              "description": "ve3"
            },
            {
              "cteamid": 1,
              "creationdate": "2016-04-30T13:39:01.860000",
              "id": "0FN94DJH903ONLH4",
              "description": "e2"
            },
            {
              "cteamid": 1,
              "creationdate": "2016-05-01T19:34:27.744000",
              "id": "7N1LP9E4E2OG81L8",
              "description": "new d"
            },
            {
              "cteamid": 1,
              "creationdate": "2016-05-01T19:36:05.462000",
              "id": "BE52E36N507DIBFF",
              "description": "old design"
            },
            {
              "cteamid": 1,
              "creationdate": "2016-05-01T19:36:33.845000",
              "id": "82F3ADJ2P67FCI8O",
              "description": "v5"
            },
            {
              "cteamid": 1,
              "creationdate": "2016-05-01T19:40:15.976000",
              "id": "9P45D3EA03ON7AL9",
              "description": "v09"
            },
            {
              "cteamid": 1,
              "creationdate": "2016-06-09T20:50:11.149083",
              "id": "EMHK5NP4K47OMHCB",
              "description": "v1"
            }
          ]
        }




## Change Team Members [/projects/{projectid}/cteams/{cteamid}/members/]

### List members of a change team  [GET]
Returns a list of usernames of users who are members of this change team.
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + cteamid: 12 (integer) - The ID of the change team in the form of an integer

+ Response 200 (application/json)

        {
          "members": [
            "ufeusr1"
          ]
        }
        

## Change Team Priorities [/projects/{projectid}/cteams/{cteamid}/priorities/]

### List change team priorities  [GET]
Returns a object that details the system priorities and rank for this change team.
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + cteamid: 12 (integer) - The ID of the change team in the form of an integer

+ Response 200 (application/json)

        {
          "priorities": [
            {
              "sysid": "1",
              "pref": "10",
              "rank": 1
            },
            {
              "sysid": "2",
              "pref": "6",
              "rank": 2
            }
          ]
        }
        


## Change Team Design Synthesis [/projects/{projectid}/cteams/{cteamid}/{synthesisid}/]

### Get design synthesis [GET]
Returns a GeoJSON feature collection object of the synthesis that is saved.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + cteamid: 12 (integer) - The ID of the change team in the form of an integer
    + synthesisid: 2G638FLMLJEGF706 (string) - The ID of a synthesis in the form of a string
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        {
            "type": "FeatureCollection",
            "features": [
                {
                    "type": "Feature",
                    "properties": {
                        "description": "new polygon",
                        "author": "ufeusr1",
                        "diagramid": 31,
                        "systag": "Small buildings, low density housing",
                        "sysname": "LDH",
                        "areatype": "project",
                        "diagramtype": "project",
                        "fundingtype": "public",
                        "cost_override": 0,
                        "cost_override_type": "per hectare.",
                        "color": "#ffcc00",
                        "min_height": 0,
                        "max_height": 0
                    },
                    "geometry": {
                        "coordinates": [
                            [
                                [
                                    -6.264439,
                                    53.332213
                                ],
                                [
                                    -6.263838,
                                    53.328984
                                ],
                                [
                                    -6.251392,
                                    53.327241
                                ],
                                [
                                    -6.241865,
                                    53.332354
                                ],
                                [
                                    -6.256371,
                                    53.338402
                                ],
                                [
                                    -6.264439,
                                    53.332213
                                ]
                            ]
                        ],
                        "type": "Polygon"
                    }
                },
                {
                    "type": "Feature",
                    "properties": {
                        "description": "AG Numeric",
                        "author": "ufeusr1",
                        "diagramid": 61,
                        "systag": "Agriculture, Forestry",
                        "sysname": "AG",
                        "areatype": "project",
                        "diagramtype": "project",
                        "fundingtype": "public",
                        "cost_override": 100,
                        "cost_override_type": "total",
                        "color": "#C2E699"
                        "min_height": 0,
                        "max_height": 0
                    },
                    "geometry": {
                        "coordinates": [
                            [
                                [
                                    -6.252637,
                                    53.329628
                                ],
                                [
                                    -6.261048,
                                    53.331012
                                ],
                                [
                                    -6.240878,
                                    53.334241
                                ],
                                [
                                    -6.252637,
                                    53.329628
                                ]
                            ]
                        ],
                        "type": "Polygon"
                    }
                }
            ]
        }


## Change Team Synthesis Timeline [/projects/{projectid}/cteams/{cteamid}/{synthesisid}/timeline/]

### Get start and end time of diagrams [GET]
Returns the start and end time of diagrams (if set) at the time of saving a design.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + cteamid: 12 (integer) - The ID of the change team in the form of an integer
    + synthesisid: 2G638FLMLJEGF706 (string) - The ID of a synthesis in the form of a string
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        {
          "timeline": {
            "6": {
              "start": "2016-11-15",
              "end": "2017-11-15"
            },
            "7": {
              "start": "2021-11-15",
              "end": "2022-11-15"
            },
            "8": {
              "start": "2021-11-15",
              "end": "2022-11-15"
            },
            "14": {
              "start": "2016-11-15",
              "end": "2017-11-15"
            },
            "15": {
              "start": "2016-11-15",
              "end": "2017-11-15"
            },
            "66": {
              "start": "2021-09-30",
              "end": "2022-09-30"
            }
          }
        }

## Change Team Synthesis Diagrams [/projects/{projectid}/cteams/{cteamid}/{synthesisid}/diagrams/]

### List diagrams in a synthesis [GET]
Returns a list of diagram IDs in the selected synthesis.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + cteamid: 12 (integer) - The ID of the change team in the form of an integer
    + synthesisid: 2G638FLMLJEGF706 (string) - The ID of a synthesis in the form of a string
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application/json)

        {
          "diagrams": [
            49,
            10,
            11,
            12,
            17,
            18
          ],
          "synthesisid": "2G638FLMLJEGF706"
        }
                

## Change Team Synthesis Policies [/projects/{projectid}/cteams/{cteamid}/{synthesisid}/policies/]

### Get policy diagrams from design [GET]
Returns a GeoJSON feature collection object of the all the policy diagrams in the synthesis that is saved.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + cteamid: 12 (integer) - The ID of the change team in the form of an integer
    + synthesisid: 2G638FLMLJEGF706 (string) - The ID of a synthesis in the form of a string
    
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application / json)

        {
          "type": "FeatureCollection",
          "features": [
            {
              "geometry": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [
                      -0.09514331817626952,
                      51.51555307745177
                    ],
                    [
                      -0.09394168853759766,
                      51.51523260058079
                    ],
                    [
                      -0.08668899536132812,
                      51.51549966479653
                    ],
                    [
                      -0.0856161117553711,
                      51.515659902574384
                    ],
                    [
                      -0.08085250854492186,
                      51.51547295844541
                    ],
                    [
                      -0.08020877838134766,
                      51.51531272000991
                    ],
                    [
                      -0.07797718048095703,
                      51.51437798456801
                    ],
                    [
                      -0.07746219635009766,
                      51.51395067054886
                    ],
                    [
                      -0.07741928100585936,
                      51.51352335252112
                    ],
                    [
                      -0.07784843444824219,
                      51.5129891993494
                    ],
                    [
                      -0.07973670959472656,
                      51.51280224425956
                    ],
                    [
                      -0.0832986831665039,
                      51.51309603048481
                    ],
                    [
                      -0.08703231811523438,
                      51.51309603048481
                    ],
                    [
                      -0.08870601654052734,
                      51.5129891993494
                    ],
                    [
                      -0.09029388427734374,
                      51.51325627671818
                    ],
                    [
                      -0.09162425994873047,
                      51.51365688983539
                    ],
                    [
                      -0.0960874557495117,
                      51.51456493319091
                    ],
                    [
                      -0.09724617004394531,
                      51.514992241447835
                    ],
                    [
                      -0.0972890853881836,
                      51.51568660881589
                    ],
                    [
                      -0.09552955627441406,
                      51.51571331504175
                    ],
                    [
                      -0.09514331817626952,
                      51.51555307745177
                    ],
                    [
                      -0.09514331817626952,
                      51.51555307745177
                    ]
                  ]
                ]
              },
              "type": "Feature",
              "properties": {
                "areatype": "project",
                "diagramtype": "project",
                "fundingtype": "other",
                "author": "ufeusr1",
                "color": "#071ac8",
                "diagramid": 5,
                "description": "testing",
                "systag": "Small buildings, low density housing",
                "cost_override": 0,
                "cost_override_type": "per hectare.",
                "min_height": 0,
                "max_height": 0
              }
            }
          ]
        }

## Change Team Synthesis Projects by System [/projects/{projectid}/cteams/{cteamid}/{synthesisid}/systems/{sysid}/projects/]

### Get project diagrams filtered by system from design [GET]
Returns a GeoJSON feature collection object of of the all the project diagrams for the given system in the saved synthesis.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + cteamid: 12 (integer) - The ID of the change team in the form of an integer
    + synthesisid: 2G638FLMLJEGF706 (string) - The ID of a synthesis in the form of a string
    + sysid: 23 (integer) - The ID of the system in the form of an integer
        
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application / json)

        {
          "type": "FeatureCollection",
          "features": [
            {
              "geometry": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [
                      -0.13423919677734375,
                      51.51536613288439
                    ],
                    [
                      -0.1297760009765625,
                      51.51344322994464
                    ],
                    [
                      -0.12805938720703125,
                      51.50981085847292
                    ],
                    [
                      -0.12874603271484375,
                      51.5091698216777
                    ],
                    [
                      -0.13286590576171875,
                      51.5091698216777
                    ],
                    [
                      -0.14247894287109375,
                      51.51173391474148
                    ],
                    [
                      -0.14385223388671875,
                      51.514084206610455
                    ],
                    [
                      -0.14934539794921875,
                      51.51792987720294
                    ],
                    [
                      -0.13767242431640625,
                      51.519425328081894
                    ],
                    [
                      -0.13423919677734375,
                      51.51536613288439
                    ],
                    [
                      -0.13423919677734375,
                      51.51536613288439
                    ]
                  ]
                ]
              },
              "type": "Feature",
              "properties": {
                "areatype": "project",
                "diagramtype": "project",
                "fundingtype": "other",
                "author": "ufeusr1",
                "color": "#331196",
                "diagramid": 10,
                "description": "ce3",
                "systag": "Small buildings, low density housing",
                "cost_override": 100,
                "cost_override_type": "total",
                "min_height": 0,
                "max_height": 0
              }
            }
          ]
        }
        

## Change Team Synthesis Projects by System [/projects/{projectid}/cteams/{cteamid}/{synthesisid}/systems/{sysid}/policies/]

### Get policy diagrams filtered by system from design [GET]
Returns a GeoJSON feature collection object of of the all the policy diagrams for the given system in the saved synthesis.

+ Parameters
    + projectid: 5c84b38a16ebeed0 (string) - The ID of a project in the form of an string
    + cteamid: 12 (integer) - The ID of the change team in the form of an integer
    + synthesisid: 2G638FLMLJEGF706 (string) - The ID of a synthesis in the form of a string
    + sysid: 23 (integer) - The ID of the system in the form of an integer
        
+ Request
    + Headers

            Authorization: Token ABC123
            
+ Response 200 (application / json)

        {
          "type": "FeatureCollection",
          "features": [
            {
              "geometry": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [
                      -0.14316558837890625,
                      51.53523137707124
                    ],
                    [
                      -0.13561248779296875,
                      51.53266860674158
                    ],
                    [
                      -0.13080596923828125,
                      51.53010569212588
                    ],
                    [
                      -0.127716064453125,
                      51.525833847122584
                    ],
                    [
                      -0.13080596923828125,
                      51.52198884392169
                    ],
                    [
                      -0.1366424560546875,
                      51.52177522311313
                    ],
                    [
                      -0.14316558837890625,
                      51.52412499689336
                    ],
                    [
                      -0.14453887939453125,
                      51.52796981972546
                    ],
                    [
                      -0.14247894287109375,
                      51.531600743186644
                    ],
                    [
                      -0.1531219482421875,
                      51.53693981046692
                    ],
                    [
                      -0.14316558837890625,
                      51.53523137707124
                    ],
                    [
                      -0.14316558837890625,
                      51.53523137707124
                    ]
                  ]
                ]
              },
              "type": "Feature",
              "properties": {
                "areatype": "policy",
                "diagramtype": "policy",
                "author": "ufeusr1",
                "fundingtype": "other",
                "color": "#331196",
                "diagramid": 12,
                "description": "656",
                "systag": "Small buildings, low density housing",
                "cost_override": 0,
                "cost_override_type": "total",
                "min_height": 0,
                "max_height": 0
              }
            }
          ]
        }